Kan 216 chat scrolling
ReginaVarybrus/talk-and-travel-chat pull request #107
Opened 2024-11-15 17:55 UTC by ValentinaHotsa

2024-11-16 21:08 UTC, ReginaVarybrus requested changes

2024-11-16 21:08 UTC, ReginaVarybrus commented on src/components/Chat/Chat.jsx
> +import ScrollToBottomButton from '../Buttons/ScrollToBottomButton/ScrollToBottomButton';
Let's named path `@/components/Buttons/...`

2024-11-18 07:57 UTC, ValentinaHotsa commented on src/components/Chat/Chat.jsx
> +import ScrollToBottomButton from '../Buttons/ScrollToBottomButton/ScrollToBottomButton';
done

2024-11-18 09:39 UTC, ReginaVarybrus approved these changes

2024-11-18 11:13 UTC, merged