KAN-92 User typing
ReginaVarybrus/talk-and-travel-chat pull request #37
Opened 2024-09-04 17:09 UTC by ReginaVarybrus

In this pull request added message "UserName is typing..." in the chat header instead of amount of partisipants when user is typing. Current user don't see this message if he is typing himself.

2024-09-06 09:29 UTC, DimaShubin requested changes

2024-09-06 09:29 UTC, DimaShubin commented on src/components/Chat/Chat.jsx
> +/* eslint-disable react/forbid-prop-types */
Why do you need it?

2024-09-06 09:29 UTC, DimaShubin commented on src/components/ChatHeader/ChatHeader.jsx
> +        <p>{`${userNameisTyping} is typing...`}</p>
It could be one paragrahp tag with conditionaly rendered text...

2024-09-06 09:29 UTC, DimaShubin commented on src/components/MessageItem/MessageItem.jsx
> +    type === MESSAGE_TYPES.START_TYPING ||
```suggestion
    [MESSAGE_TYPES.START_TYPING, MESSAGE_TYPES.STOP_TYPING].includes(type)
```
I just don't like those operators ||

2024-09-06 09:29 UTC, DimaShubin commented on src/components/MessageList/MessageList.jsx
> +/* eslint-disable react/forbid-prop-types */
???

2024-09-06 20:16 UTC, ValentinaHotsa approved these changes
So far I don’t see anything that needs to be changed, but I understand that madness awaits us with resolving conflicts with our branches 🫠

2024-09-12 08:04 UTC, DimaShubin approved these changes

2024-09-12 13:19 UTC, merged