Feature/recovery password
ReginaVarybrus/talk-and-travel-chat pull request #91
Opened 2024-11-08 05:37 UTC by ValentinaHotsa

2024-11-08 15:12 UTC, ReginaVarybrus requested changes

2024-11-08 15:12 UTC, ReginaVarybrus commented on src/components/RegisterForm/RegisterForm.styled.js
> +  @media (min-width: 768px) {
Let's use mediaQueries.js

2024-11-10 10:17 UTC, ValentinaHotsa commented on src/components/RegisterForm/RegisterForm.styled.js
> +  @media (min-width: 768px) {
done

2024-11-10 12:08 UTC, ReginaVarybrus approved these changes

2024-11-10 12:11 UTC, merged